#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dbxtool
Version  : 338a2d097b79faba9505a913c2cfc5916b6ffa9a
Release  : 3
URL      : https://github.com/rhboot/dbxtool/archive/338a2d097b79faba9505a913c2cfc5916b6ffa9a.tar.gz
Source0  : https://github.com/rhboot/dbxtool/archive/338a2d097b79faba9505a913c2cfc5916b6ffa9a.tar.gz
Summary  : Secure Boot DBX updater
Group    : Development/Tools
License  : GPL-2.0
Requires: dbxtool-bin = %{version}-%{release}
Requires: dbxtool-data = %{version}-%{release}
Requires: dbxtool-man = %{version}-%{release}
Requires: dbxtool-services = %{version}-%{release}
BuildRequires : pkgconfig(efivar)
BuildRequires : popt-dev

%description
This package contains DBX updates for UEFI Secure Boot.

%package bin
Summary: bin components for the dbxtool package.
Group: Binaries
Requires: dbxtool-data = %{version}-%{release}
Requires: dbxtool-man = %{version}-%{release}
Requires: dbxtool-services = %{version}-%{release}

%description bin
bin components for the dbxtool package.


%package data
Summary: data components for the dbxtool package.
Group: Data

%description data
data components for the dbxtool package.


%package doc
Summary: doc components for the dbxtool package.
Group: Documentation
Requires: dbxtool-man = %{version}-%{release}

%description doc
doc components for the dbxtool package.


%package man
Summary: man components for the dbxtool package.
Group: Default

%description man
man components for the dbxtool package.


%package services
Summary: services components for the dbxtool package.
Group: Systemd services

%description services
services components for the dbxtool package.


%prep
%setup -q -n dbxtool-338a2d097b79faba9505a913c2cfc5916b6ffa9a

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550090805
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550090805
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dbxtool

%files data
%defattr(-,root,root,-)
/usr/share/dbxtool/DBXUpdate-2016-08-09-13-16-00.bin

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/dbxtool/*

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dbxtool.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/dbxtool.service
